### ISSUE TITLE
Component usage as props not working

### ISSUE THREAD

**Issue by linyuqing222** [Mohamed-Kaizen/unplugin-svelte-components#21]
Hello,

I'm encountering an issue where components used as props seem not to be recognized during the build process.
Here's a snippet of my configuration:

```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    components({
      dirs: 'src/components',
      dts: 'src/components.d.ts',
      external: [
        {
          from: 'svelte-routing',
          names: ['Link', 'Route', 'Router'],
          defaultImport: false,
        },
      ],
    }),
  ],
  // ...
})
```

And here is how I'm using the components in my Svelte app:
```svelte
// App.svelte
<Router>
  <Route path="/" component={ListPage} />
</Router>
```

While `Router` and `Route` work as expected, during the build process I receive an error stating that `ListPage` is not defined.
I believe this might be a limitation when using components as props, which is a feature I find very useful. Would it be possible to extend the functionality to support components used in this manner?
Thank you for your work on this plugin and for considering this enhancement.

Best regards

**Comment by Mohamed-Kaizen** [comment]
Hi @kevin82222,

This is an interesting feature, but I have a couple of questions before implementing it.

* First, how can we figure out whether a prop is a component or not? For example, if the user creates a local variable with the same name as a component in the auto-imports folder, it will be difficult to tell which import is correct. Here is an example:

    ```svelte
    <script>
      import ListPage from "X"; // this will be auto-imported by unplugin-svelte-components, because the user passed `ListPage` as a prop in the component
    
      let ListPage = "Something"; // this is a variable the user created that will be passed to the component
    </script>
    
    <Route path="/" component={ListPage} />
    ```
  This is most likely to cause an error, because the user created a prop with the same name as a component, and unplugin-svelte-components found the component with that name and tried to import it.


* Second, while we checking whether a prop is a component, that may slow down development and build times? This is because we would need to check every component that the user uses and check its props.
