### ISSUE TITLE
vite v4 type error

### ISSUE THREAD

**Issue by initred** [Mohamed-Kaizen/unplugin-svelte-components#9]
Type error in vite v4. in vite.config.ts

Other functions work well without any problems.

<img width="728" alt="스크린샷_20230201_114113" src="https://user-images.githubusercontent.com/34208843/216074869-8b08fb48-063c-4533-a651-8d45698563b6.png">

Thank you for making such a good package.

**Comment by Mohamed-Kaizen** [comment]
Hi @initred, Sorry for the late reply.

The thing is if you import it like `import Components from "unplugin-svelte-components/dist/vite"`, typescript will not complain about the missing types because all the files are in the dist folder.

But if you update latest version of unplugin-svelte-components, it will work as expected.

If updating to the latest version work for you, please don't forget to close the issue :)

Thanks for the report and thanks for using unplugin-svelte-components :) .

**Comment by initred** [comment]
@Mohamed-Kaizen I will update the version and close the issue after checking. Thank you very much. Good luck.

**Comment by initred** [comment]
@Mohamed-Kaizen I just checked that it works properly after updating with the latest package.
I hope this package gets a lot of stars. If you do well documenting the repository's About and ReadMe.md files, you will be able to gain more stars and fame.

**Comment by Mohamed-Kaizen** [comment]
ok thanks  :)
